services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gastosapp-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: src/GastosApp.API/Dockerfile
    container_name: gastosapp-api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=db;Database=GastosAppDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;"
      Jwt__Key: "CAMBIAR_ESTA_CLAVE_SECRETA_POR_UNA_PROPIA_DE_AL_MENOS_32_CARACTERES"
      FrontendUrl: "http://localhost:5173"
    ports:
      - "8080:8080"

volumes:
  db_data:
